import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The `learn` and `extend` sidebars are defined manually so that grouping and
 * labels are decoupled from the folder/URL structure. The remaining sidebars
 * are still generated from the filesystem.
 */
const sidebars: SidebarsConfig = {
  gettingStarted: [{type: 'autogenerated', dirName: 'getting-started'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
  community: [{type: 'autogenerated', dirName: 'community'}],
  about: [{type: 'autogenerated', dirName: 'about'}], // problem with loading license.md

  learn: [
    {type: 'doc', id: 'learn/index', label: 'Overview'},
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        {type: 'doc', id: 'learn/tutorials/rt-task', label: 'Reaction-time task tutorial'},
        {type: 'doc', id: 'learn/tutorials/survey-instrument', label: 'Survey instrument tutorial'},
        {type: 'doc', id: 'learn/tutorials/community-tutorials', label: 'Community tutorials'},
      ],
    },
    {
      type: 'category',
      label: 'Core concepts',
      items: [
        {type: 'doc', id: 'learn/concepts/timeline', label: 'The timeline'},
        {type: 'doc', id: 'learn/concepts/plugins', label: 'Plugins'},
        {type: 'doc', id: 'learn/concepts/extensions', label: 'Extensions'},
        {type: 'doc', id: 'learn/concepts/dynamic-parameters', label: 'Dynamic parameters'},
        {type: 'doc', id: 'learn/concepts/data', label: 'The data object'},
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Customize the look & feel',
          items: [
            {type: 'doc', id: 'learn/guides/style', label: 'Controlling visual appearance'},
            {type: 'doc', id: 'learn/guides/fullscreen', label: 'Fullscreen mode'},
            {type: 'doc', id: 'learn/guides/progress-bar', label: 'Showing a progress bar'},
          ],
        },
        {
          type: 'category',
          label: 'Present media & surveys',
          items: [
            {type: 'doc', id: 'learn/guides/building-surveys', label: 'Building surveys'},
            {type: 'doc', id: 'learn/guides/media-preloading', label: 'Preloading media'},
          ],
        },
        {
          type: 'category',
          label: 'Control how the experiment runs',
          items: [
            {type: 'doc', id: 'learn/guides/experiment-options', label: 'Experiment-wide settings'},
            {type: 'doc', id: 'learn/guides/events', label: 'Responding to events'},
          ],
        },
        {
          type: 'category',
          label: 'Collect & manage data',
          items: [
            {type: 'doc', id: 'learn/guides/storing-data', label: 'Storing and exporting data'},
            {type: 'doc', id: 'learn/guides/eye-tracking', label: 'Eye tracking'},
            {type: 'doc', id: 'learn/guides/record-browser-interactions', label: 'Recording browser interactions'},
          ],
        },
        {
          type: 'category',
          label: 'Ensure data quality',
          items: [
            {type: 'doc', id: 'learn/guides/simulation', label: 'Testing with simulation mode'},
            {type: 'doc', id: 'learn/guides/timing-accuracy', label: 'Timing accuracy'},
            {type: 'doc', id: 'learn/guides/browser-device-support', label: 'Browser & device support'},
            {type: 'doc', id: 'learn/guides/exclude-browser', label: 'Excluding participants by browser features'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy & recruit',
      items: [
        {type: 'doc', id: 'learn/deploy/running-experiments', label: 'Hosting and running experiments'},
        {type: 'doc', id: 'learn/deploy/prolific', label: 'Integrating with Prolific'},
        {type: 'doc', id: 'learn/deploy/mturk', label: 'Integrating with Mechanical Turk'},
      ],
    },
  ],

  extend: [
    {type: 'doc', id: 'extend/index', label: 'The jsPsych ecosystem'},
    {type: 'doc', id: 'extend/browse', label: 'Browse the ecosystem'},
    {
      type: 'category',
      label: 'Build a plugin',
      items: [
        {type: 'doc', id: 'extend/plugins/plugin-tutorial', label: 'Plugin tutorial'},
        {type: 'doc', id: 'extend/plugins/plugin-components', label: 'Anatomy of a plugin'},
      ],
    },
    {type: 'doc', id: 'extend/extensions/extension-development', label: 'Build an extension'},
    {type: 'doc', id: 'extend/build-a-timeline', label: 'Build a timeline'},
    {type: 'doc', id: 'extend/publish-and-share', label: 'Publish & share'},
    {
      type: 'category',
      label: 'Contribute to the core project',
      items: [
        {type: 'doc', id: 'extend/contributing/contributing', label: 'Contributing to jsPsych'},
        {type: 'doc', id: 'extend/contributing/dev-environment', label: 'Setting up the dev environment'},
        {type: 'doc', id: 'extend/contributing/documentation', label: 'Writing documentation'},
      ],
    },
  ],
};

export default sidebars;
